#!/usr/bin/env bash
# Displays information about a domain and its subdomains
# shellcheck disable=SC2086


get_rec () {
	rec=$(dig "$URL" | grep "^$URL" | awk '{print $4}')
	return 0
}
get_ip () {
	IP=$(dig "$URL" | grep "^$URL" | awk '{print $5}')
	return 0	
}

if [ "$2" ]
then
	URL="$2.$1"
	get_rec
	get_ip
	echo The subdomain "$2" is a "$rec" record and points to "$IP"
else
	URL="$1"
	get_rec
	get_ip
	echo The subdomain www is a "$rec" record and points to "$IP"
	URL="lb-01.$1"
	get_rec
	get_ip
	echo The subdomain lb-01 is a "$rec" record and points to "$IP"
	URL="web-01.$1"
	get_rec
	get_ip
	echo The subdomain web-01 is a "$rec" record and points to "$IP"
	URL="web-02.$1"
	get_rec
	get_ip
	echo The subdomain web-02 is a "$rec" record and points to "$IP"
fi

exit 0
