#!/usr/bin/env bash
# Displays information about a domain and its subdomains


get_rec () {
	rec=$(dig "$URL" | grep "^$URL" | awk '{print $4}')
	return 0
}
get_ip () {
	IP=$(dig "$URL" | grep "^$URL" | awk '{print $5}')
	return 0	
}

if [ "$2" ]
then
	URL="$2.$1"
	get_rec
	get_ip
	echo The subdomain "$URL" is a "$rec" record and points to "$IP"
else
	URL="$1"
	get_rec
	get_ip
	echo The subdomain www."$URL" is a "$rec" record and points to "$IP"
	echo The subdomain lb-01."$URL" is a "$rec" record and points to "$IP"
	URL="web-01.$1"
	get_rec
	get_ip
	echo The subdomain "$URL" is a "$rec" record and points to "$IP"
	URL="web-02.$1"
	get_rec
	get_ip
	echo The subdomain "$URL" is a "$rec" record and points to "$IP"
fi

exit 0
