#!/usr/bin/env bash
# Script to configure and install nginx

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

sudo ufw allow 'Nginx HTTP'
sudo service nginx start
