#!/usr/bin/env bash
# Script to configure and install nginx

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

sudo ufw allow 'Nginx HTTP'
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://youtu.be/v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx start
