#!/usr/bin/env bash
# Script to configure and install nginx

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo ufw allow 'Nginx HTTP'
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://youtube.com/ permanent;" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server;/a error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx start
