#!/usr/bin/env bash
# Configure a load balancer server with HAProxy 1.8

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy

echo \
"
frontend localnodes
	bind *:80
	mode http
	default_backend nodes

backend nodes
	mode http
	balance roundrobin
	server 1088-web-01 35.243.137.210
	server 1088-web-02 34.73.37.244" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
