#!/usr/bin/env bash
# Prints a message 10 times, and with special messages for the 4th and 8th
i=1
while [ $i -lt 11 ]
do
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	(( i++ ))
done
